[package]
name = "tron-zero-server"
version = "0.3.0"
edition = "2024"

[dependencies]
shared = { path = "../shared", package = "tron-zero-shared" }
bevy.workspace = true
lightyear = { workspace = true, features = ["udp", "raw_connection", "input_native"] }
rand.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json = "1"
ureq = { version = "3", features = ["json"] }
ctrlc = "3"
